-- Deleted projects release their key for a new active project.
-- The old index name was generated by TypeORM, so locate and remove it safely.
DO $$
DECLARE
  old_index text;
BEGIN
  SELECT index_name INTO old_index
  FROM (
    SELECT indexrelid::regclass::text AS index_name, pg_get_indexdef(indexrelid) AS definition
    FROM pg_index
    WHERE indrelid = 'projects'::regclass
      AND indisunique
  ) indexes
  WHERE definition LIKE '%(key)%'
    AND definition NOT LIKE '%WHERE%'
  LIMIT 1;

  IF old_index IS NOT NULL THEN
    EXECUTE format('DROP INDEX IF EXISTS %s', old_index);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_projects_active_key"
  ON projects (key)
  WHERE deleted_at IS NULL;

-- The backlog and sprint views filter active tickets by project and sprint,
-- then sort by board order. This keeps that query responsive as it grows.
CREATE INDEX IF NOT EXISTS "IDX_tickets_active_project_sprint_order"
  ON tickets (project_id, sprint_id, board_order, "createdAt")
  WHERE deleted_at IS NULL;
