/** Centralized environment variable keys, mirrored by the validation schema. */
export enum EnvVar {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  CORS_ORIGIN = 'CORS_ORIGIN',
  SHOW_SWAGGER = 'SHOW_SWAGGER',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
  DATABASE_URL = 'DATABASE_URL',
  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',
  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
}
